### ISSUE TITLE
OAuth2: Is it possible to use OAuth2 with self hosted GitLab?

### ISSUE THREAD

**Issue by TooFeD** [answerdev/plugins#5]
I'm trying to configure OAuth2 with self-hosted GitLab server (which using LDAP for own authentication).
I did test all OAuth configs with Postman and everything is fine.
I'm getting x509 issue when I'm trying to authorize via OAuth2.

`ERROR	/go/src/github.com/answerdev/answer/answer_build3894253293/vendor/github.com/answerdev/answer/internal/controller/connector_controller.go:112 connector received failed: code exchange failed: Post "https://gitlab.myserver.com/oauth/token": x509: certificate signed by unknown authority`

I'm using k8s deployment with official helm-chart. How to provide my custom certificate?

**Comment by TooFeD** [comment]
Certificate provided by my IT Department, so let's encrypt is not an option there. Insecure could be an option. 
1) Should I add insecure option to startup docker parameters?
Or
2) How to add my CA.pem to answer container?

**Comment by joyqi** [comment]
Answer is using alpine as its base docker image.

```dockerfile
FROM answerdev/answer:latest

COPY my-cert.pem /usr/local/share/ca-certificates/my-cert.crt

RUN cat /usr/local/share/ca-certificates/my-cert.crt >> /etc/ssl/certs/ca-certificates.crt
```

I think you can add your private root CA manually, and re-build it.
